CREATE TABLE USERS
(
	ID DECIMAL(18,0) PRIMARY KEY  NOT NULL IDENTITY (1,1),
	USR_NAME NVARCHAR(50) NOT NULL,
	USR_PASS NVARCHAR(50) NOT NULL,
	USR_FULL_NAME NVARCHAR(1000) NOT NULL,
	USR_ROLE_ID DECIMAL(18,0) NOT NULL,
	USR_ADDRESS NVARCHAR(MAX),
	USR_PHONE DECIMAL(10) NOT NULL,
	USR_EMAIL NVARCHAR(1000),
	USR_GENDER INT,
	USER_DATE_OF_BIRTH DATETIME,
	USR_CREATED_BY NVARCHAR(1000),
	USR_CREATED_DATE DATETIME,
	USR_ACTIVE INT
);

CREATE TABLE USER_INFORMATION
(
	ID DECIMAL(18,0) PRIMARY KEY  NOT NULL IDENTITY(1,1),
	USR_ID DECIMAL(18,0) NOT NULL,
	USR_TYPE INT NOT NULL,
	USR_LEGAL_TYPE INT NOT NULL,
	USR_LEGAL_ID NVARCHAR(100) NOT NULL,
	USR_REGISTER_START_DATE DATETIME,
	USR_REGISTER_END_DATE DATETIME,
	CREATED_BY NVARCHAR(1000),
	CREATED_DATE DATETIME,
	DOCUMENT_ID DECIMAL(18,0),
	USR_STATUS INT
);

CREATE TABLE USER_TYPE
(
	ID INT PRIMARY KEY NOT NULL,
	USER_TYPE_NAME NVARCHAR(MAX) NOT NULL
)

CREATE TABLE SYS_ROLES
(
	ROLE_ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	ROLE_NAME NVARCHAR(MAX) NOT NULL,
	DESCRIPTION NVARCHAR(MAX)
);

CREATE TABLE SYS_PERMISSIONS
(
	PERMISSION_ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	PERMISSION_NAME NVARCHAR(MAX),
	DESCRIPTION NVARCHAR(MAX)
);

CREATE TABLE SYS_ROLE_PERMISSION
(
	ROLE_ID INT,
	PERMISSION_ID INT
);


CREATE TABLE CORE_SUBJECTS
(
	SUBJECT_ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	SUBJECT_NAME NVARCHAR(MAX),
	DESCRIPTIONS NVARCHAR(MAX),
	STATUS INT
);

CREATE TABLE CORE_QUESTIONS
(
	QUESTION_ID DECIMAL(18,0) PRIMARY KEY NOT NULL IDENTITY(1,1),
	SUBJECT_ID INT,
	CONTENT NVARCHAR(MAX),
	LEVEL INT,
	ANSWERS NVARCHAR(MAX),
	QUESTION_TYPE INT,
	STATUS INT
);

CREATE TABLE CORE_QUESTION_TYPE
(
	QUESTION_TYPE_ID INT,
	QUESTION_TYPE_NAME NVARCHAR(MAX)
);

CREATE TABLE CORE_EXAMS
(
	EXAM_ID DECIMAL(18,0) PRIMARY KEY NOT NULL IDENTITY(1,1),
	SUBJECT_ID INT,
	EXAM_NAME NVARCHAR(MAX),
	DURATION INT,
	TOTAL_QUESTION INT,
	STATUS INT
);

CREATE TABLE CORE_EXAM_QUESTION
(
	EXAM_ID DECIMAL(18,0),
	QUESTION_ID DECIMAL(18,0)
);

CREATE TABLE SYS_DOCUMENT
(
	DOCUMENT_ID DECIMAL(18,0) PRIMARY KEY IDENTITY(1,1) NOT NULL,
	DOCUMENT_NAME NVARCHAR(MAX),
	DOCUMENT_TYPE INT,
	DOCUMENT_CONTENT NTEXT,
	CREATED_BY DECIMAL(18,0),
	CREATED_DATE DATETIME,
	STATUS INT
)
